import "@tanstack/react-start/server-only";
// Static JSON, ~130KB, generated by tools/n8n-ingest/compact-node-schemas.mjs
// from yigitkonur/n8n-schema-generator. Re-run that script and copy the
// output here to refresh against a newer n8n version.
import nodeSchemaIndex from "./n8n-knowledge/node-schema-index.json";

interface NodeSchemaEntry {
  displayName: string;
  group: string[];
  resources?: string[];
  operations?: string[];
  required?: string[];
}
interface SchemaIndex {
  n8nVersion: string;
  nodeCount: number;
  nodes: Record<string, NodeSchemaEntry>;
  credentials: Record<string, { displayName: string; requiredFields: string[] }>;
}

const index = nodeSchemaIndex as unknown as SchemaIndex;

export interface WorkflowValidationIssue {
  nodeName: string;
  nodeType: string;
  message: string;
}

/** Static, pre-deploy sanity check against real n8n {n8nVersion} node
 *  schemas — catches the two most common ways AI-generated workflow JSON
 *  is wrong (a node "type" that doesn't exist, or a "resource"/"operation"
 *  combination that isn't valid for that node) BEFORE spending a live
 *  test-deploy round trip on the owner's n8n instance. This is a cheap
 *  first filter, not a replacement for testDeployWorkflow() — n8n's own
 *  create-workflow endpoint remains the source of truth since parameter
 *  shapes go deeper than this index tracks. */
export function validateWorkflowAgainstSchema(workflowJson: Record<string, unknown>): WorkflowValidationIssue[] {
  const issues: WorkflowValidationIssue[] = [];
  const nodes = Array.isArray(workflowJson["nodes"]) ? (workflowJson["nodes"] as Record<string, unknown>[]) : [];

  for (const node of nodes) {
    const type = typeof node["type"] === "string" ? (node["type"] as string) : "";
    const name = typeof node["name"] === "string" ? (node["name"] as string) : "(unnamed)";
    if (!type) {
      issues.push({ nodeName: name, nodeType: type, message: "Node has no type." });
      continue;
    }
    // Only validate core n8n-nodes-base types — community/langchain nodes
    // aren't in this index and shouldn't be flagged as unknown.
    if (!type.startsWith("n8n-nodes-base.")) continue;

    const schema = index.nodes[type];
    if (!schema) {
      issues.push({
        nodeName: name,
        nodeType: type,
        message: `"${type}" isn't a recognized n8n core node type (index built against n8n ${index.n8nVersion}) — likely hallucinated or renamed/removed.`,
      });
      continue;
    }

    const params = (node["parameters"] as Record<string, unknown> | undefined) ?? {};
    const resource = params["resource"];
    if (schema.resources && typeof resource === "string" && !schema.resources.includes(resource)) {
      issues.push({
        nodeName: name,
        nodeType: type,
        message: `resource "${resource}" isn't valid for ${schema.displayName} — expected one of: ${schema.resources.join(", ")}.`,
      });
    }
    const operation = params["operation"];
    if (schema.operations && typeof operation === "string" && !schema.operations.includes(operation)) {
      issues.push({
        nodeName: name,
        nodeType: type,
        message: `operation "${operation}" isn't valid for ${schema.displayName} — expected one of: ${schema.operations.join(", ")}.`,
      });
    }
  }

  return issues;
}

export function schemaIndexSummary(): string {
  return `${index.nodeCount} core n8n node types indexed against n8n ${index.n8nVersion}.`;
}
